version: '3'

services:
  aspnetcore:
    image: myapp
    environment: 
      - "ASPNETCORE_ENVIRONMENT=Production"
    ports: 
      - "5000:80"
    build:
      context: ../docker/out
      dockerfile: Dockerfile
